### ISSUE TITLE
מפגש מחר 30/4/2021

### ISSUE THREAD

**Issue by motaztamimi** [MustafaAbuGhannam/website_project#22]
כל אחד בבקשה ירשום השעה המתאימה לו למפגש

**Comment by khader-zatari** [comment]
من ال ١١ لل ٤ والمسا بعد نص الليل

**Comment by MustafaAbuGhannam** [comment]
I have work tomorrow tell 7 pm , but I will be available after that ,
you can  start the meeting without me

**Comment by motaztamimi** [comment]
יופי מחכה שאר הצוות לשלוח 
אחר כך נודיע באיזה שעה מתאים 
**לתשומת לבכם כתיבה  בגית  רק באנגלית או עברית 
תודה

**Comment by mahmoud22z44** [comment]
انا فاضي على ال٣

**Comment by motaztamimi** [comment]
מטרת המפגש היא לדון במיסמות שבוע שעבר 
+ דיון במיסמות הפרויקט באופן כללי 
לגבי המסימות הבאות בנתיים לא יהיה לכולכם מסימות חדשות לפני שנעשה פגישה עם הארגון כדי לקחת את הפיידפאק  שלהם על העבודות אחר כך לקחת מהם פרטיים יותר לדפים בפניים 

ואם אחד מהצצות  צריך יותר זמן  על המסימה שלו לסיבה כל שהיית מוזמן לבקש מחר

**Comment by mazen-Qaissi** [comment]
I will be available at 2 PM

**Comment by motaztamimi** [comment]
אוקי מחר מוסטפא מתשדל להיכנס מוקדם ולקחת הפסקה מחר המפגש בשעה 15.00 נא לא לאחר בבקשה
זה הקישור לזום לילה טוב
מועתז תמימי . is inviting you to a scheduled Zoom meeting.

Topic: מועתז תמימי .'s Personal Meeting Room

Join Zoom Meeting
https://us04web.zoom.us/j/6073343075?pwd=S09ycjJobTJlVjhBZkZ1ejBMRTlWUT09

Meeting ID: 607 334 3075
Passcode: 3iQvYw
